# PCF8574 I/O Expander https://esphome.io/components/pcf8574#pcf8574-i-o-expander
#   Configuration variables: https://esphome.io/components/pcf8574#configuration-variables
#     * id (Required, ID): The id to use for this PCF8574 component.
#     * address (Optional, int): The IÂ²C address of the driver. Defaults to 0x21.
#     * pcf8575 (Optional, boolean): Whether this is a 16-pin PCF8575. Defaults to false.
#   Pin configuration variables:
#     * pcf8574 (Required, ID): The id of the PCF8574 component of the pin.
#     * number (Required, int): The pin number.
#     * inverted (Optional, boolean): If all read and written values should be treated as inverted. Defaults to false.
#     * mode (Optional, string): A pin mode to set for the pin at. One of INPUT or OUTPUT.
#
# GPIO Switch https://esphome.io/components/switch/gpio#gpio-switch
#   Configuration variables: https://esphome.io/components/switch/gpio#configuration-variables
#     * pin (Required, Pin Schema): The GPIO pin to use for the switch.
#     * interlock (Optional, list): A list of other GPIO switches in an interlock group. See Interlocking.
#     * interlock_wait_time (Optional, Time): For interlocking mode, set how long to wait after other items in an interlock group have been disabled before re-activating. Useful for motors where immediately turning on in the other direction could cause problems.
#     * All other options from Switch.
#   Active Low Switch https://esphome.io/components/switch/gpio#active-low-switch
#   Momentary Switch https://esphome.io/components/switch/gpio#momentary-switch
#   Interlocking https://esphome.io/components/switch/gpio#interlocking


switch:
# Individual output hub4
  - platform: gpio
    name: "_40"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_41"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_42"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_43"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_44"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_45"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_46"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_47"
    pin:
      pcf8574: ${id_pcf8574}4
      number: 7
      mode:
        output: true
      inverted: false
# Individual output hub5
# switch:
  - platform: gpio
    name: "_50"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_51"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_52"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_53"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_54"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_55"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_56"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_57"
    pin:
      pcf8574: ${id_pcf8574}5
      number: 7
      mode:
        output: true
      inverted: false
# Individual output hub6
# switch:
  - platform: gpio
    name: "_60"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_61"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_62"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_63"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_64"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_65"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_66"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_67"
    pin:
      pcf8574: ${id_pcf8574}6
      number: 7
      mode:
        output: true
      inverted: false
# Individual output hub7
# switch:
  - platform: gpio
    name: "_70"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_71"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_72"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_73"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_74"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_75"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_76"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "_77"
    pin:
      pcf8574: ${id_pcf8574}7
      number: 7
      mode:
        output: true
      inverted: false